# Ultralytics YOLO ğŸš€, AGPL-3.0 license
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
datasetname: MOVEHomoDETDataset_stream #MOVEDETDataset MOVEHomoDETDataset_stream MOVEHomoDETDataset
path: /data/jiahaoguo/dataset/gaode_all/gaode_5  # dataset root dir
style: one
train: annotations/yolo/train.txt  # train images (relative to 'path') 4 images
val: annotations/yolo/test.txt  # val images (relative to 'path') 4 images
test:  annotations/yolo/test.txt # test images (optional)
labels_dir: annotations/yolo/
images_dir: images/

val_reimgsz: True
split_length: [8, 50] #å…ˆä½¿ç”¨10çš„ç‰‡æ®µè®­ç»ƒï¼Œå†50 "all"è¡¨ç¤ºä¸åˆ‡å‰²


match_number: 1 #   å½“å‰å¸§å‰åå„å–ä¸€å…±å‡ ä¸ªå…³è¿å¸§ï¼Œmatch_number=2å³å‰åå„å–ä¸€ä¸ª
interval: 2    # å–å¾—å¸§é—´éš”å½“å‰å¸§

rho: 4

#coco eval
eval_ann_json: /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/coco/test.json
classes_map: [0,1]
# Classes
names:
  0: static
  1: moving