# Ultralytics YOLO ğŸš€, AGPL-3.0 license
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]

# train:gaode_5 test:gaode_6
train: /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/yolo/gaode_5.txt
train_labels_dir: /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/yolo/
train_images_dir: /data/jiahaoguo/dataset/gaode_all/gaode_5/images/

val: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/gaode_6.txt  
val_labels_dir: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/
val_images_dir: /data/jiahaoguo/dataset/gaode_6/images/

test: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/gaode_6.txt  
test_labels_dir: /data/jiahaoguo/dataset/gaode_6/annotations/yolo/
test_images_dir: /data/jiahaoguo/dataset/gaode_6/images/

datasetname: MOVEHomoDETDataset_stream #MOVEDETDataset MOVEHomoDETDataset_stream MOVEHomoDETDataset
style: muti #one or muti
val_reimgsz: True
split_length: [10, 50] #å…ˆä½¿ç”¨10çš„ç‰‡æ®µè®­ç»ƒï¼Œå†50 "all"è¡¨ç¤ºä¸åˆ‡å‰²


match_number: 1 #   å½“å‰å¸§å‰åå„å–ä¸€å…±å‡ ä¸ªå…³è¿å¸§ï¼Œmatch_number=2å³å‰åå„å–ä¸€ä¸ª
interval: 2    # å–å¾—å¸§é—´éš”å½“å‰å¸§

rho: 4

#coco eval
eval_ann_json: /data/jiahaoguo/dataset/gaode_all/gaode_5/annotations/cocoVID/test_vid.json
classes_map: [0,1]
# Classes
names:
  0: static
  1: moving